apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-config-service
  namespace: train-ticket
  labels:
    app: ts-config-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ts-config-service
  template:
    metadata:
      labels:
        app: ts-config-service
    spec:
      serviceAccountName: train-ticket-sa
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: workload
                    operator: In
                    values:
                      - wnode2
                      - wnode3
                      - wnode4
      containers:
        - name: ts-config-service
          image: nexus-svc.nexus.svc.cluster.local:8082/truelykh/ts-config-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 15679
              name: http
          env:
            - name: NACOS_ADDRS
              value: "nacos:8848"
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: JAVA_OPTS
              value: "-Xms32m -Xmx120m -XX:+UseSerialGC -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:+ExitOnOutOfMemoryError"
          resources:
            requests:
              cpu: 20m
              memory: 120Mi
            limits:
              cpu: 150m
              memory: 190Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ts-config-service
  namespace: train-ticket
  labels:
    app: ts-config-service
spec:
  type: ClusterIP
  selector:
    app: ts-config-service
  ports:
    - name: http
      port: 15679
      targetPort: 15679
