apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: train-ticket
  labels:
    app: redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload
                    operator: In
                    values:
                      - wnode5
      containers:
        - name: redis
          image: redis:alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              name: port

          resources:
            requests:
              cpu: 25m
              memory: 48Mi
            limits:
              cpu: 150m
              memory: 96Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: train-ticket
  labels:
    app: redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - name: port
      port: 6379
      targetPort: 6379
