apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: argocd
  name: argocd-sa

---
apiVersion: v1
kind: Pod
metadata:
  name: argocd
  namespace: argocd
  labels:
    app: argocd-pod
spec:
  serviceAccountName: argocd-sa
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: workload
                operator: In
                values:
                  - wnode1
  containers:
    - name: argocd
      image: quay.io/argoproj/argocd:v3.1.8
      command:
        - argocd-server
      args:
        - --insecure
      ports:
        - containerPort: 8080
          name: admin
        - containerPort: 8003
          name: metrics
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  namespace: argocd
  name: argocd-pod-svc
  labels:
    app: argocd-pod-svc
spec:
  selector:
    app: argocd-pod
  type: NodePort
  ports:
    - name: admin
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 8003
      targetPort: 8003
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-role
  namespace: argocd
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
      - pods
      - services
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-rolebinding
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: argocd-sa
    namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-role
